

- name: Import periodic class-list
  uri:
    url: "{{ clistimpperiapi }}"
    method: PUT
    return_content: yes
    status_code: 200
    body_format: json
    body: "{{ clistimportperiodictest }}"
    validate_certs: False
    headers:
      Content-Type: "application/json"
      Authorization: "A10 {{ a10signature }}"
  register: clist_import_periodic

- debug:
    msg: "{{ clist_import_periodic }}"
